services:
  ephemeral-production-web:
    image: ghcr.io/afonsodemori/ephemeral-web:${EPHEMERAL_PRODUCTION_WEB_TAG:?}
    environment:
      NODE_ENV: ${EPHEMERAL_PRODUCTION_WEB_NODE_ENV:?}
      NUXT_PUBLIC_WEBSITE_HOST: ${EPHEMERAL_PRODUCTION_WEB_NUXT_PUBLIC_WEBSITE_HOST:?}
      NUXT_PUBLIC_SHORTCUT_REDIRECTION_BASE_URL: ${EPHEMERAL_PRODUCTION_WEB_NUXT_PUBLIC_SHORTCUT_REDIRECTION_BASE_URL:?}
      DB_HOST: ${EPHEMERAL_PRODUCTION_WEB_DB_HOST:?}
      DB_PORT: ${EPHEMERAL_PRODUCTION_WEB_DB_PORT:?}
      DB_USER: ${EPHEMERAL_PRODUCTION_WEB_DB_USER:?}
      DB_PASS: ${EPHEMERAL_PRODUCTION_WEB_DB_PASS:?}
      DB_NAME: ${EPHEMERAL_PRODUCTION_WEB_DB_NAME:?}
      JWT_SECRET: ${EPHEMERAL_PRODUCTION_WEB_JWT_SECRET:?}
      JWT_EXPIRATON_TIME_IN_MINUTES: ${EPHEMERAL_PRODUCTION_WEB_JWT_EXPIRATON_TIME_IN_MINUTES:?}
      JWT_REFRESH_SECRET: ${EPHEMERAL_PRODUCTION_WEB_JWT_REFRESH_SECRET:?}
      JWT_REFRESH_EXPIRATON_TIME_IN_DAYS: ${EPHEMERAL_PRODUCTION_WEB_JWT_REFRESH_EXPIRATON_TIME_IN_DAYS:?}
      GITHUB_CLIENT_ID: ${EPHEMERAL_PRODUCTION_WEB_GITHUB_CLIENT_ID:?}
      GITHUB_CLIENT_SECRET: ${EPHEMERAL_PRODUCTION_WEB_GITHUB_CLIENT_SECRET:?}
    depends_on:
      - postgres
    restart: unless-stopped
