services:
  meteosaucana-production-web:
    image: registry.gitlab.com/afonsodemori/jrb-meteosaucana:${METEOSAUCANA_PRODUCTION_WEB_TAG:?}
    environment:
      DB_HOST: ${METEOSAUCANA_PRODUCTION_WEB_DB_HOST:?}
      DB_PORT: ${METEOSAUCANA_PRODUCTION_WEB_DB_PORT:?}
      DB_NAME: ${METEOSAUCANA_PRODUCTION_WEB_DB_NAME:?}
      DB_USER: ${METEOSAUCANA_PRODUCTION_WEB_DB_USER:?}
      DB_PASS: ${METEOSAUCANA_PRODUCTION_WEB_DB_PASS:?}
    depends_on:
      - postgres
    restart: always
