services:
  mycrew-staging-api:
    image: registry.gitlab.com/my-crew-app/my-crew-api:${MYCREW_STAGING_API_TAG:?}
    environment:
      NODE_ENV: ${MYCREW_STAGING_API_NODE_ENV:?}
      APP_VERSION: ${MYCREW_STAGING_API_APP_VERSION:?}
      APP_BUILD_AT: ${MYCREW_STAGING_API_APP_BUILD_AT:?}
      APP_BASE_URL: ${MYCREW_STAGING_API_APP_BASE_URL:?}
      WEB_BASE_URL: ${MYCREW_STAGING_API_WEB_BASE_URL:?}
      DATABASE_URL: ${MYCREW_STAGING_API_DATABASE_URL:?}
      EMAIL_SERVICE_ENABLED: ${MYCREW_STAGING_API_EMAIL_SERVICE_ENABLED:?}
      RESEND_API_KEY: ${MYCREW_STAGING_API_RESEND_API_KEY:?}
      JWT_SECRET: ${MYCREW_STAGING_API_JWT_SECRET:?}
    depends_on:
      - postgres
    restart: always
